### ISSUE TITLE
outline thunks

### ISSUE THREAD

**Issue by rossibarra** [kjgilbert/NSF_PRFB_PlantGenome#2]
1) estimate DFE, test against teosinte: 
- DoFE  
- simulate for variety of Vg, Vd, etc.  
- test against observed traits: compare effect size distribution

2) simulate maize domestication:  
- add domestication bottleneck, variety of selection regimes for different Vg, etc.
- compare to actual traits  

3) simulate additional populations:  
- look for impact of additional demography, selection on how traits might differ among pops of the domesticate

Ideas: 
- validate with qx to test for selection?
- test in population with both teosinte and maize alleles so effect sizes are comparable?

**Comment by kjgilbert** [comment]
Thoughts added to updated outline.
